development: &development
  protocol: 'http'
  host: <%= ENV['ARANGODB_1_PORT_8529_TCP_ADDR'] || 'localhost' %>
  port: <%= ENV['ARANGODB_1_PORT_8529_TCP_PORT'] || 8529 %>
  password: ''
  username: ''
  database: <%= ENV['ARANGODB_DATABASE_NAME'] || 'stargazer' %>

production:
  <<: *development
